version: 1

disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    fmt: "%(asctime)s %(levelname)s %(name)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
  matrix_log_file:
    class: logging.FileHandler
    formatter: json
    filename: logs/matrix.log.json
    level: DEBUG
  core_log_file:
    class: logging.FileHandler
    formatter: json
    filename: logs/core.log.json
    level: DEBUG
  tree_logger:
    class: logging.FileHandler
    formatter: json
    filename: logs/tree.log.json
    level: DEBUG

root:
  handlers: ["console"]
  level: INFO

loggers: {}
